urls.py
from django.conf.urls.defaults import *
from django.conf import settings
from django.views.generic.simple import direct_to_template
from django.contrib import admin

import os.path

admin.autodiscover()

urlpatterns = patterns('',
	(r'^ads/', include('ts.urls')),
	(r'^calendar/', include('calendarer.urls')),
	(r'^contact/', include('contact.urls')),	
	(r'^profile/', include('profiler.urls')),
	(r'^photologue/', include('photologue.urls')),
	(r'^search/', include('search.urls')),
	(r'^pages/', include('pages.urls')),
	(r'^$', include('homepage.urls')),
    (r'^error/', include('redirect.urls')),
	(r'^admin/', include(admin.site.urls)),
    (r'^admin/doc/', include('django.contrib.admindocs.urls')),
	(r'^my_admin/jsi18n', 'django.views.i18n.javascript_catalog'),
)

if settings.DEBUG:
    urlpatterns += patterns('',
        (r'^site_media/(?P<path>.*)$', 'django.views.static.serve',
            {'document_root': os.path.join(os.path.dirname(__file__), "site_media")}),
    )

admin.site.root_path = '/admin/'

apps/ts/models.py
# ts/models.py
from django.db import models
from datetime import datetime, timedelta
from django.contrib.auth.models import User
from photologue.models import Photo, Gallery
from django.utils.safestring import mark_safe
import settings
if "mailer" in settings.INSTALLED_APPS:
    from mailer import send_mail
else:
    from django.core.mail import send_mail
from BeautifulSoup import BeautifulSoup
from BeautifulSoup import Comment as BSComment
from markdown import markdown


def _make_html_text(markdown_text):
	regular_text = markdown(markdown_text)
	return regular_text

VALID_TAGS = {'strong': [],'em': [],'p': [],'ol': [],'ul': [],'li': [],'br': [],'quote':[],'h1':[],'h2':[],'hr':[],'a': ['href', 'title'],'table':[],'tr':[],'th':[],'td':[],}

def _sanitize_html(value, valid_tags=VALID_TAGS):
    soup = BeautifulSoup(value)
    comments = soup.findAll(text=lambda text:isinstance(text, BSComment))
    [comment.extract() for comment in comments]
    # Some markup can be crafted to slip through BeautifulSoup's parser, so
    # we run this repeatedly until it generates the same output twice.
    newoutput = soup.renderContents()
    while 1:
        oldoutput = newoutput
        soup = BeautifulSoup(newoutput)
        for tag in soup.findAll(True):
            if tag.name not in valid_tags:
                tag.hidden = True
            else:
                tag.attrs = [(attr, value) for attr, value in tag.attrs if attr in valid_tags[tag.name]]
        newoutput = soup.renderContents()
        if oldoutput == newoutput:
            break
    return newoutput


def _make_flat_text(markdown_text):
	lineless = markdown_text.replace('\n',' ')
	spaceless = ''.join(BeautifulSoup(lineless).findAll(text=True))
	return spaceless
	
ADTYPES = ((1,'Free'),(2,'Bronze'),(3,'Silver'),(4,'Gold'),)
PRICETYPES = ((1,'Per Night'),(2,'Per Week'),)


class Photoo(Photo):
	orderer = models.IntegerField(default=1,blank=True, null=True)
	
	class Meta:
		ordering = ['orderer']
		get_latest_by = "orderer"
		
	def ad(self):
		try:
			return self.ad_set.all()[0]
		except Exception, e:
			return 'hello'
			
	def user(self):
		try:
			return self.ad_set.all()[0].creator
		except Exception, e:
			return 'hello'

class Country(models.Model):
	name = models.CharField(blank=True,  max_length=128)
	iso = models.CharField(max_length=20,)
	
	class Meta:
		verbose_name = 'Country'
		verbose_name_plural = 'Countries'
		ordering = ('name',)
		
	def __unicode__(self):
		return self.name
	
	def flag(self):
		return mark_safe('<img src="/site_media/images/flagsbig/' + str(self.iso) + '.png" style="width:80px;"></img>')
	flag.allow_tags=True


class Comment(models.Model):
	comment = models.TextField(blank=True)
	user = models.ForeignKey(User)
	premod = models.BooleanField(default=False)
	date_created = models.DateField(blank=True,auto_now_add=True)
	
	def __unicode__(self):
		return str(self.user) + ' - ' + str(self.id) + ' - ' + str(self.comment[0:20])


	
class Resort(models.Model):
	name = models.CharField(max_length=200)
	slug = models.SlugField(max_length=200)	
	branch = models.CharField(max_length=200,blank=True, null=True)
	description = models.TextField(blank=True, null=True)
	picture = models.ForeignKey(Photo, blank=True, null=True)
	email = models.EmailField(blank=True, null=True)
	url = models.URLField(blank=True, null=True)
	address = models.CharField(max_length=200, blank=True,)
	address_country = models.ForeignKey(Country,blank=True,null=True)
	premod = models.BooleanField(default=False)
	comment = models.ManyToManyField(Comment, blank=True, null=True)
	
	def __unicode__(self):
		return self.name
	class Meta:
		verbose_name = 'Resort'
		verbose_name_plural = 'Resorts'
		ordering = ('name',)


class Ad(models.Model):
	name = models.CharField(max_length=80)
	slug = models.SlugField(max_length=100)
	description = models.TextField()
	descriptionflat = models.TextField(blank=True)
	descriptionhtml = models.TextField(blank=True)
	photos = models.ManyToManyField(Photoo, blank=True, null=True)
	resort = models.ForeignKey(Resort, blank=True, null=True)
	creator = models.ForeignKey(User)
	start_ad = models.DateField(blank=True,auto_now_add=True)
	start_room = models.DateField(blank=True)
	end_room = models.DateField(blank=True)
	adtype = models.IntegerField(choices=ADTYPES,blank=True, null=True)
	premod = models.BooleanField(default=False)
	paid = models.BooleanField(default=False)
	expiration_date = models.DateField(blank=True,)
	price = models.DecimalField(max_digits=10, decimal_places=2)
	priceunit = models.IntegerField(choices=PRICETYPES,blank=True, null=True)
			# alter table ts_ad add column descriptionhtml longtext not null;
			# alter table ts_ad add column descriptionflat longtext not null;		
	class Meta:
		ordering = ('-start_ad',)
		permissions = (('view_paypal','Can see the results of Paypal auth return.'),)

	def __unicode__(self):
		return self.name

	def first(self):
		for photo in self.photos.all():
			if photo.orderer == 1:
				return photo
				break

	def photolist(self):
		return self.photos.order_by('orderer')

	def save(self,*args,**kwargs):
		s = self
		dhtml = _make_html_text(s.description)
		try:
			chtml = _sanitize_html(dhtml, valid_tags=VALID_TAGS)
		except Exception, e:
			chtml = "Sorry we can't retrieve this post right now."
		s.descriptionhtml = chtml
		s.descriptionflat = _make_flat_text(chtml)
		new = True
		try:		# this checks to see if it is new or not
			a = Ad.objects.get(id=s.id)
			new = False
			action = 'edited'
		except Exception, e:
			a = None
			action = 'created'
		super(Ad, self).save(*args,**kwargs)
		subject = 'TSR: An ad was just %s. %s'  %(action,self.name)
		content = '''Annie,
				%s just %s the ad %s.
				Check it for moderation <a href='http://timesharerentals.com/admin/ts/ad/%s/'>here</a> when you get a chance.
				
				Timesharerentals.com
		''' %(self.creator,action,self.name,self.id)
		fromemail = settings.CONTACT_EMAIL
		toemail = ['modernarrangements@gmail.com',]
		send_mail(subject,content,fromemail,toemail)



class Email(models.Model):
	EVENT_CHOICES = ((1,'Ad is Created'),(2,'TS is available'),(3,'TS is done being available'),(4,'Ad expires'),)
	name = models.CharField(max_length=100)
	content = models.TextField()
	days = models.IntegerField(blank=True, null=True)
	event = models.IntegerField(choices=EVENT_CHOICES,blank=True, null=True)
	
	def __unicode__(self):
		return self.name
		

apps/ts/forms.py
# ts/forms.py
from django import forms
from django.contrib.admin import widgets
from datetime import datetime, timedelta
import settings
from ts.models import Ad, Country, Photoo, Resort, PRICETYPES
from ts.widgets import Dateranger



class AdForm(forms.ModelForm):
	name = forms.CharField(widget=forms.TextInput(attrs={'size':'35'}))
	description = forms.CharField(widget=forms.Textarea(attrs={'cols':'50'}))
	addedresortname = forms.CharField(widget=forms.TextInput(attrs={'size':'35'}),label='Name of Resort',required=False)
	start_room = forms.CharField(widget=forms.TextInput(attrs={'size':'8'}),label='Start Date')
	end_room = forms.CharField(widget=forms.TextInput(attrs={'size':'8'}),label='End Date')
	price = forms.CharField(widget=forms.TextInput(attrs={'size':'8'}),label='Price USD')
	priceunit = forms.ChoiceField(choices=PRICETYPES,label='Pricing Term',required=True)
		
	class Meta:
		model = Ad
		exclude = ('creator','adtype','premod','photos','expiration_date')
		fields = ('name','description','resort','addedresortname','start_room','end_room','price','priceunit')

	def clean_price(self):
		data = self.cleaned_data['price']
		try:
			int(data)
		except Exception, e:
			raise forms.ValidationError('Please enter a number')
		return data

	 
# class EditAdForm(forms.ModelForm):
# 	name = forms.CharField(widget=forms.TextInput(attrs={'size':'35'}))
# 	description = forms.CharField(widget=forms.Textarea(attrs={'cols':'50'}))
# 	addedresortname = forms.CharField(widget=forms.TextInput(attrs={'size':'35'}),label='Name of Resort',required=False)
# 	start_room = forms.CharField(widget=forms.TextInput(attrs={'size':'8'}),label='Start Date')
# 	end_room = forms.CharField(widget=forms.TextInput(attrs={'size':'8'}),label='End Date')
# 	price = forms.CharField(widget=forms.TextInput(attrs={'size':'8'}),label='Price')
# 		
# 	class Meta:
# 		model = Ad
# 		exclude = ('creator','adtype','premod','photos','expiration_date')
# 		fields = ('name','description','resort','addedresortname','start_room','end_room','price',)



class AdPicForm(forms.ModelForm):
	caption = forms.CharField(widget=forms.Textarea(attrs={'cols':'30','rows':'3'}))

	class Meta:
		model = Photoo
		exclude = ('title_slug','date_added','tags','is_public','crop_from','effect','title','orderer')

	def __init__(self, ad, *args, **kwargs):
		super(AdPicForm, self).__init__(*args, **kwargs)
		mypics = ad.photos.all()
		self.fields['deleter'] = forms.ModelChoiceField(queryset=mypics,label='Select photo to delete.',required=False,)

templates/create/add_pictures.html
{# templates/create/add_pictures.html #}
{% extends "base.html" %}

{% block head_title %}Add Photos to your Ad{% endblock head_title %}

{% block extra_head %}
	<style type="text/css" media="screen">
		#sortable{list-style-type:none;width:640px;margin:0 auto;}
		#sortable li{width:100px;height:125px;float:left;margin:2px;padding:0 8px 5px 8px;background:wheat;border:3px solid #F2D686;cursor:pointer;}
		#sortable .deleteselected{border:3px solid red;-moz-border-radius:5px;-webkit-border-radius:5px;}
		.thisbuttoner{width:100px;float:right;}
		.thumbboxprev{float:left;margin:0 15px 0 0;cursor:pointer;}
		.thumbboxprevspacer{width:16px;float:left;margin:0 15px 0 0;}
		.thumbboxnext{float:left;margin:0 0 0 0;cursor:pointer;}
		.thumbboxdelete{cursor:pointer;float:right;}
		#message{display:none;margin:0 0 30px 180px;font-size:15px;}
		#grayboxholder{width:100%;height:0;}
			#graybox{display:none;background:rgba(90,90,90,.5);width:630px;height:270px;position:relative;top:5px;left:130px;-moz-border-radius:20px;-webkit-border-radius:20px;}
		#graybox #loading{width:32px;height:32px;margin:115px 0 0 305px;}
		.extrapic{margin:0px 0 0 365px;}
		.dnd{margin:0 0 0 200px;}
	</style>
	<script type="text/javascript" charset="utf-8">
		$(document).ready(function(){
			showntf = {% if ad.canaddmore %}1{% else %}0{% endif %};
			$idd = $('#id_deleter').parent().parent();
			$idd.hide();
			if(showntf==0){
				$('#newthumbform').hide();
				$('#message').show();
			}
			$('.thumbboxdelete').click(function(){
				$('.thumbbox').removeClass('deleteselected');
				whichone = $(this).attr('id').split('-')[1];
				$(this).parent().addClass('deleteselected');
				$('#id_deleter').val(whichone);
				$('#newthumbform').show();
				$idd.hide();
			})
			var times = 0;
			$(function(){
				$("#sortable").sortable({
					update:function(e,ui){
						var order = $("#sortable").sortable('toArray');
						$('#graybox').css({'display':'block'});						// put up a gray box and a progress wheel
						url = '/ads/create/picture/order/{{ ad.id }}/?order=' + String(order);
						$.get(url,function(data){
							result = JSON.parse(data);
							$('#graybox').css({'display':'none'});
						})
					}
				});
				$( "#sortable" ).disableSelection();
			});
		});
	</script>
{% endblock extra_head %}

{% block body %}
	<div class="section" id="wide_column">
		<a href='{% url profile user.id %}' class='buttoner thisbuttoner'>Cancel</a>
		<h1>Add Photos to</h1>
		<h2>{{ ad.get_adtype_display }} Ad - {{ ad }}</h2><br/><br/>
		<div id='grayboxholder'><div id='graybox'><img src="/site_media/images/loading2.gif" id="loading"></img></div></div>
		<div class='thumbnails'>
			{% ifnotequal ad.adtype 1 %}
				<div class='dnd'>Drag and drop to re-order your photos.</div>
			{% endifnotequal %}
			{% if ad.photolist %}
				<ul id="sortable">
				{% for photo in ad.photolist %}
					<li class="thumbbox" id="list-{{ forloop.counter }}">
						{{ photo.caption }}<br/>
						<img src="{{ photo.get_thumbnail_url }}"></img><br/>
						<img src="/admin_media/img/admin/icon_deletelink.gif" class="thumbboxdelete" id="tbd-{{ photo.id }}"></img>
					</li>
				{% endfor %}
				</ul>
			{% else %}
				<p class='extrapic'>You have not uploaded any photos yet.</p>
			{% endif %}
			<p class='clearer'></p>
			{% if ad.howmanymore %}
				<p class='extrapic'>You can add {{ ad.howmanymore }} more picture{{ ad.howmanymore|pluralize }}.</p>
			{% endif %}
		</div>{# end of thumbnails #}
		
		<div class='clearer'></div>

		<form enctype="multipart/form-data" method="POST" action="." class='' id='newthumbform'>
			{% include 'includes/form.html' %}
			<p></p>
		</form><br/><br/><br/>
		<div id='message'>Please select a photo to delete before adding a new one.</div>
		<a href='{% url profile user.id %}' class='buttoner thisbuttoner'>Go to my profile</a><br/>
	</div>
{% endblock %}


{# can add more pictures - yes/no #}
{# can add x more pictures #}

templates/create/chart.html
{# templates/create/chart.html #}
{% extends "base.html" %}

{% block head_title %}Create and Ad{% endblock head_title %}
{% block extra_head %}
	<script src="/site_media/js/jquery.qtip.min.js" type="text/javascript" charset="utf-8"></script>
	<script type="text/javascript" charset="utf-8">
		$(document).ready(function(){
			// $('.pmhelp').hover(function(e){
			// 	alert('hover');
			// },function(){
			// 	
			// })
			$('.pmhelp').qtip({
				// content:'Private Messaging allows you to send and receive messages with other timesharerentals.com members without revealing your email address.',
				content:'Private Messaging allows you to send messages to other timesharerentals.com members and receive messages from anyone interested in your timeshare without revealing your email address.',
				style:{background:'#ccc',border:{color:'#aaa',width:.025,radius:5}},
				show:'mouseover',
				hide:'mouseout'
			})
		});
	</script>
	<style type="text/css" media="screen">
		.section{padding-left:0px;padding-right:0px;}
		#wide_column{width:916px;}
		.section h1{padding:0 0 20px 20px;}
		.pmhelp{float:right;margin-right:15px;color:#EE2A7B;font-weight:bold;font-size:14px;cursor:pointer;}
	</style>
{% endblock %}

{% block body %}
	<div class="section" id="wide_column">
		<h1>Select the ad that's right for you</h1>

		<div class="graph">
			<div class="graphrow graphheader">
				<div id='col1'><h2 class='freeh2'>Free</h2><h3><span>&#36;</span>{{ photats.1.dollars }}</h3></div>
				<div id='col2'><h2 class='bronzeh2'>Bronze</h2><h3><span>&#36;</span>{{ photats.2.dollars }}</h3></div>
				<div id='col3'><h2 class='silverh2'>Silver</h2><h3><span>&#36;</span>{{ photats.3.dollars }}</h3></div>
				<div id='col4'><h2 class='goldh2'>Gold</h2><h3><span>&#36;</span>{{ photats.4.dollars }}</h3></div>
			</div><div class='clearer'></div>
			<div class="graphrow graphpics darkrow">
				<div>
					<a href="{% url newadcreate 'free' %}" class='picchart'>
						<img src="/site_media/images/adlogos/freetag.png" class="adtag" alt="bt_free"></img>
					</a>
				</div>
				<div>
					<a href="{% url newadcreate 'bronze' %}"  class='picchart'>
						<img src="/site_media/images/adlogos/bronzetag.png" class="adtag" alt="bronze"></img>
					</a>
				</div>
				<div>
					<a href="{% url newadcreate 'silver' %}"  class='picchart'>
						<img src="/site_media/images/adlogos/silvertag.png" class="adtag" alt="silver"></img>
					</a>
				</div>
				<div>
					<a href="{% url newadcreate 'gold' %}"  class='picchart'>
						<img src="/site_media/images/adlogos/goldtag.png" class="adtag" alt="gold"></img>
					</a>
				</div>
			</div><div class='clearer'></div>
			<div class="graphrow graphlower">
				<div>Description: {{ photats.1.description }}</div>
				<div>Description: {{ photats.2.description }}</div>
				<div>Description: {{ photats.3.description }}</div>
				<div>Description: {{ photats.4.description }}</div>
			</div><div class='clearer'></div>
			<div class="graphrow graphlower darkrow">
				<div>{{ photats.1.numphotos }} picture</div>
				<div>{{ photats.2.numphotos }} pictures</div>
				<div>{{ photats.3.numphotos }} pictures</div>
				<div>{{ photats.4.numphotos }} pictures</div>
			</div><div class='clearer'></div>
			<div class="graphrow graphlower">
				<div>&nbsp;</div>
				<div>Featured Listing</div>
				<div>Featured Listing</div>
				<div>Featured Listing</div>
			</div><div class='clearer'></div>
			<div class="graphrow graphlower darkrow">
				<div>Ad Length: 1 month</div>
				<div>Ad Length: 6 months</div>
				<div>Ad Length: 12 months</div>
				<div>Ad Length: Lifetime</div>
			</div><div class='clearer'></div>
			<div class="graphrow graphlower">
				<div>Private Messaging<span class='pmhelp'>?</span></div>
				<div>Private Messaging<span class='pmhelp'>?</span></div>
				<div>Private Messaging<span class='pmhelp'>?</span></div>
				<div>Private Messaging<span class='pmhelp'>?</span></div>
			</div><div class='clearer'></div>
			<div class="graphrow graphlower darkrow">
				<div>Inline Ads</div>
				<div>No Ads</div>
				<div>No Ads</div>
				<div>No Ads</div>
			</div><div class='clearer'></div>
			<div class="graphrow graphpics">
				<div>
					<a href="{% url newadcreate 'free' %}" class='picchart'>
						<img src="/site_media/images/adlogos/freetag.png" class="adtag" alt="bt_free"></img>
					</a>
				</div>
				<div>
					<a href="{% url newadcreate 'bronze' %}"  class='picchart'>
						<img src="/site_media/images/adlogos/bronzetag.png" class="adtag" alt="bronze"></img>
					</a>
				</div>
				<div>
					<a href="{% url newadcreate 'silver' %}"  class='picchart'>
						<img src="/site_media/images/adlogos/silvertag.png" class="adtag" alt="silver"></img>
					</a>
				</div>
				<div>
					<a href="{% url newadcreate 'gold' %}"  class='picchart'>
						<img src="/site_media/images/adlogos/goldtag.png" class="adtag" alt="gold"></img>
					</a>
				</div>
			</div><div class='clearer'></div>
		</div>
	</div>
{% endblock %}











{# <div class="section" id="wide_column"> #}
{# 	<h1>Which ad is right for you?</h1><br/><br/> #}
{# 	<table class="graph"> #}
{# 		<div> #}
{# 			<div id='firstcol'></div><div id='secondcol'><h2 class='freeh2'>Free</h2></div><div id='divirdcol'><h2 class='bronzeh2'>Bronze</h2></div><div id='divirdcol'><h2 class='silverh2'>Silver</h2></div><div id='divirdcol'><h2 class='goldh2'>Gold</h2></div> #}
{# 		</div> #}
{# 		<div> #}
{# 			<div class='descgraph'>Words</div><div>40 words</div><div>100 words</div><div>unlimited words</div><div>unlimited words</div> #}
{# 		</div> #}
{# 		<div> #}
{# 			<div class='descgraph'>Pictures</div><div>1 pictures</div><div>3 pictures</div><div>10 pictures</div><div>10 pictures</div> #}
{# 		</div> #}
{# 		<div> #}
{# 			<div class='descgraph'>Featured Listing</div><div>no</div><div>yes</div><div>yes</div><div>yes</div> #}
{# 		</div> #}
{# 		<div> #}
{# 			<div class='descgraph'>Lengdiv</div><div>2 mondivs</div><div>6 mondivs</div><div>12 mondivs</div><div>Lifetime</div> #}
{# 		</div> #}
{# 		<div> #}
{# 			<div class='descgraph'>Private Messaging</div><div>yes</div><div>yes</div><div>yes</div><div>yes</div> #}
{# 		</div> #}
{# 		<div> #}
{# 			<div class='descgraph'>Statistics</div><div>no</div><div>yes</div><div>yes</div><div>yes</div> #}
{# 		</div> #}
{# 		<div> #}
{# 			<div class='descgraph'>Price</div><div>Free</div><div>$80</div><div>$120</div><div>$250</div> #}
{# 		</div> #}
{# 		<div> #}
{# 			<div class='descgraph'>&nbsp;</div> #}
{# 			<div> #}
{# 				<a href="{% url newadcreate 'free' %}" class='picchart'> #}
{# 					<img src="/site_media/images/adlogos/freetag.png" class="adtag" alt="bt_free"></img> #}
{# 				</a> #}
{# 			</div> #}
{# 			<div> #}
{# 				<a href="{% url newadcreate 'bronze' %}"  class='picchart'> #}
{# 					<img src="/site_media/images/adlogos/bronzetag.png" class="adtag" alt="bronze"></img> #}
{# 				</a> #}
{# 			</div> #}
{# 			<div> #}
{# 				<a href="{% url newadcreate 'silver' %}"  class='picchart'> #}
{# 					<img src="/site_media/images/adlogos/silvertag.png" class="adtag" alt="silver"></img> #}
{# 				</a> #}
{# 			</div> #}
{# 			<div> #}
{# 				<a href="{% url newadcreate 'gold' %}"  class='picchart'> #}
{# 					<img src="/site_media/images/adlogos/goldtag.png" class="adtag" alt="gold"></img> #}
{# 				</a> #}
{# 			</div> #}
{# 		</div> #}
{# 	</table> #}
{# </div> #}

templates/create/newadcreate.html
{# templates/create/newadcreate.html #}
{% extends "base.html" %}

{% block head_title %}Create a {{ adtype|capfirst }} Ad{% endblock head_title %}
{% block extra_head %}
	<link rel="stylesheet" href="/site_media/css/ui-lightness/jquery-ui-1.8.14.custom.css" type="text/css" media="screen" title="no title" charset="utf-8">
	<script type="text/javascript" charset="utf-8">
		$(document).ready(function(){
			$arn = $('#id_addedresortname').parent().parent();		// this is the whole form row for the added resort field
			$arn.css({'display':'none'});
			$('#id_resort').change(function(){
				if($("#id_resort option:selected").text() == "--My resort isn't here. Add a new one."){
					$arn.slideDown('slow');
				}else{
					$arn.hide();
				};
			})
			$(function(){
				$('#id_start_room').datepicker({dateFormat:'yy-mm-dd'});
				$('#id_end_room').datepicker({dateFormat:'yy-mm-dd'});
			})
			m1 = "<img src='/admin_media/img/admin/icon-unknown.gif' class='helper'><span class='popupholder'><div class='popup' id='icon-";
			m2 = "'>";
			m3 = "</div></span>";
			$('#id_name').after(m1+'id_name'+m2+'Give your timeshare ad a name that people will be able to find, like "Beatiful Oceanside Villa".'+m3);
			$('#id_description').after(m1+'id_description'+m2+'Be sure to include the number of bedrooms and bathrooms as well as a general description about the timeshare.'+m3);
			$('#id_resort').after(m1+'id_resort'+m2+"Pick the resort where your timeshare is located."+m3);
			$('#id_start_room').after(m1+'id_start_room'+m2+'Select the first day your timeshare will be available for rent.'+m3);
			$('#id_end_room').after(m1+'id_end_room'+m2+'Select the last day your timeshare will be available for rent.'+m3);
			$('#id_price').after(m1+'id_price'+m2+'How much will you charge (in US Dollars) to rent your timeshare?'+m3);
			$('.helper').hover(function(e){
				which = $(this).prev().attr('id');
				$('#icon-' + which).css({'display':'block'});
			},function(){
				$('#icon-' + which).css({'display':''});
			})
		});
	</script>
	<style type="text/css" media="screen">
		.helper{width:15px;height:15px;padding-left:10px;cursor:pointer;}
		.popupholder{height:1px;width:1px;margin-left:10px;display:inline;position:relative;left:20px;top:-40px;}
		.popup{display:none;width:180px;background:rgba(200,200,200,.95);color:#7AAA1B;font-size:13px;
			-moz-border-radius:5px;-webkit-border-radius:5px;padding:4px 15px 7px 15px;border:1px solid #888;position:absolute;left:1px;top:24px;}
	</style>
{% endblock extra_head %}

{% block body %}
	<div class="section" id="wide_column">
		<img src="/site_media/images/adlogos/{{ adtype }}.png" class="right" alt="bt_free"></img>
		<h1 class="adformh1">
			{{ adtype|capfirst }} Ad
		</h1>
		<form action="." method="POST">
			{% include 'includes/form.html' %}
		</form>
		<div class="somediv"></div>
	</div>{# end of section #}
{% endblock %}