apps/profiler/urls.py
# profiler/urls.py
from django.conf.urls.defaults import *
from django.contrib import admin

admin.autodiscover()

urlpatterns = patterns('',
	# url(r'^login/$', 'django.contrib.auth.views.login', name='login'),
	url(r'^login/$', 'profiler.views.login_view', name='login_view'),
	url(r'^logout/$', 'django.contrib.auth.views.logout', name='logout'),
	url(r'^create-new-user/$', 'profiler.views.newuser', name='newuser'),
	url(r'^user-created/$', 'profiler.views.usercreated', name='usercreated'),
	url(r'^forgot/$', 'profiler.views.forgot_view',name='forgot_view'),
	url(r'^forgot/submit/$', 'profiler.views.forgot_submit',name='forgot_submit'),
	url(r'^password-reset/confirmation/$', 'profiler.views.passwordreset_submit', name='passwordreset_submit'),
	url(r'^password-reset/(?P<key>[-\w]+)/$', 'profiler.views.passwordreset', name='passwordreset'),
    url(r'^(?P<username>[\w\-]+)/change-password/$', 'profiler.views.changepassword', name='changepassword'),
    url(r'^(?P<username>[\w\-]+)/change-email/$', 'profiler.views.changeemail', name='changeemail'),
	
	url(r'^$','profiler.views.allusers', name='allusers',),
	url(r'^messages/(?P<user_id>\d+)/$', 'profiler.views.messages', name='messages'),
	url(r'^messages/(?P<user_id>\d+)/(?P<message_id>\d+)/$', 'profiler.views.message', name='message'),
	url(r'^messages/(?P<user_id>\d+)/compose/(?P<object_id>\d+)/(?P<reco>[-\w]+)/$', 'profiler.views.compose', name='compose'),
	url(r'^settings/(?P<user_id>\d+)/$', 'profiler.views.usersettings', name='usersettings'),
	url(r'^(?P<user_id>\d+)/$', 'profiler.views.profile', name='profile'),
)

urls.py
from django.conf.urls.defaults import *
from django.conf import settings
from django.views.generic.simple import direct_to_template
from django.contrib import admin

import os.path

admin.autodiscover()

urlpatterns = patterns('',
	(r'^ads/', include('ts.urls')),
	(r'^calendar/', include('calendarer.urls')),
	(r'^contact/', include('contact.urls')),	
	(r'^profile/', include('profiler.urls')),
	(r'^photologue/', include('photologue.urls')),
	(r'^search/', include('search.urls')),
	(r'^pages/', include('pages.urls')),
	(r'^$', include('homepage.urls')),
    (r'^error/', include('redirect.urls')),
	(r'^admin/', include(admin.site.urls)),
    (r'^admin/doc/', include('django.contrib.admindocs.urls')),
	(r'^my_admin/jsi18n', 'django.views.i18n.javascript_catalog'),
)

if settings.DEBUG:
    urlpatterns += patterns('',
        (r'^site_media/(?P<path>.*)$', 'django.views.static.serve',
            {'document_root': os.path.join(os.path.dirname(__file__), "site_media")}),
    )

admin.site.root_path = '/admin/'

apps/profiler/models.py
# profiler.models
from django.db import models
from datetime import datetime, timedelta
from django.contrib.auth.models import User
from django.utils.safestring import mark_safe
import settings
from django.conf import settings
if "mailer" in settings.INSTALLED_APPS:
    from mailer import send_mail
else:
    from django.core.mail import send_mail
from ts.models import Ad



class Mess(models.Model):
	sender = models.ForeignKey(User,related_name='messsend',blank=True,null=True)
	receiver = models.ForeignKey(User,related_name='messrec')
	email = models.EmailField(blank=True)
	name = models.CharField(blank=True, max_length=100)
	subject = models.CharField(max_length=200,blank=False)
	message = models.TextField(blank=False)
	written = models.DateTimeField(auto_now_add=True)
	unread = models.BooleanField(default=True)
	replied = models.ForeignKey('self',blank=True,null=True)

	def __unicode__(self):
		return self.subject 
	
	class Meta:
		ordering = ('-written',)

	def save(self):
		super(Mess, self).save()
		s = self
		subject = 'TimeshareRentals.com message: ' + self.subject
		if self.sender:
			content = '''%s,

			%s sent you a message on TimeshareRentals.com with the subject "%s".

			Message: %s


			You can respond <a href='http://timesharerentals.com/profile/messages/%s/%s/'>here</a>.

			Thank you,
			TimeshareRentals.com
			''' %(self.receiver.username,self.receiver.username,self.subject,self.message,self.receiver.id,self.id)
		else:
			content = '''%s,

			%s, with the email: %s sent you a message on TimeshareRentals.com with the subject "%s".

			Message: %s


			You can respond <a href='http://timesharerentals.com/profile/messages/%s/%s/'>here</a>.

			Thank you,
			TimeshareRentals.com
			''' %(self.receiver.username,self.name,self.email,self.subject,self.message,self.receiver.id,self.id)
		fromemail = settings.CONTACT_EMAIL
		toemail = [self.receiver.email,]
		send_mail(subject,content,fromemail,toemail)



class EmailReset(models.Model):
	email = models.EmailField(blank=True, max_length=100)
	expires = models.DateTimeField()
	key = models.CharField(blank=True, max_length=100)
	
	def __unicode__(self):
		return self.email

apps/ts/models.py
# ts/models.py
from django.db import models
from datetime import datetime, timedelta
from django.contrib.auth.models import User
from photologue.models import Photo, Gallery
from django.utils.safestring import mark_safe
import settings
if "mailer" in settings.INSTALLED_APPS:
    from mailer import send_mail
else:
    from django.core.mail import send_mail
from BeautifulSoup import BeautifulSoup
from BeautifulSoup import Comment as BSComment
from markdown import markdown


def _make_html_text(markdown_text):
	regular_text = markdown(markdown_text)
	return regular_text

VALID_TAGS = {'strong': [],'em': [],'p': [],'ol': [],'ul': [],'li': [],'br': [],'quote':[],'h1':[],'h2':[],'hr':[],'a': ['href', 'title'],'table':[],'tr':[],'th':[],'td':[],}

def _sanitize_html(value, valid_tags=VALID_TAGS):
    soup = BeautifulSoup(value)
    comments = soup.findAll(text=lambda text:isinstance(text, BSComment))
    [comment.extract() for comment in comments]
    # Some markup can be crafted to slip through BeautifulSoup's parser, so
    # we run this repeatedly until it generates the same output twice.
    newoutput = soup.renderContents()
    while 1:
        oldoutput = newoutput
        soup = BeautifulSoup(newoutput)
        for tag in soup.findAll(True):
            if tag.name not in valid_tags:
                tag.hidden = True
            else:
                tag.attrs = [(attr, value) for attr, value in tag.attrs if attr in valid_tags[tag.name]]
        newoutput = soup.renderContents()
        if oldoutput == newoutput:
            break
    return newoutput


def _make_flat_text(markdown_text):
	lineless = markdown_text.replace('\n',' ')
	spaceless = ''.join(BeautifulSoup(lineless).findAll(text=True))
	return spaceless
	
ADTYPES = ((1,'Free'),(2,'Bronze'),(3,'Silver'),(4,'Gold'),)
PRICETYPES = ((1,'Per Night'),(2,'Per Week'),)


class Photoo(Photo):
	orderer = models.IntegerField(default=1,blank=True, null=True)
	
	class Meta:
		ordering = ['orderer']
		get_latest_by = "orderer"
		
	def ad(self):
		try:
			return self.ad_set.all()[0]
		except Exception, e:
			return 'hello'
			
	def user(self):
		try:
			return self.ad_set.all()[0].creator
		except Exception, e:
			return 'hello'

class Country(models.Model):
	name = models.CharField(blank=True,  max_length=128)
	iso = models.CharField(max_length=20,)
	
	class Meta:
		verbose_name = 'Country'
		verbose_name_plural = 'Countries'
		ordering = ('name',)
		
	def __unicode__(self):
		return self.name
	
	def flag(self):
		return mark_safe('<img src="/site_media/images/flagsbig/' + str(self.iso) + '.png" style="width:80px;"></img>')
	flag.allow_tags=True


class Comment(models.Model):
	comment = models.TextField(blank=True)
	user = models.ForeignKey(User)
	premod = models.BooleanField(default=False)
	date_created = models.DateField(blank=True,auto_now_add=True)
	
	def __unicode__(self):
		return str(self.user) + ' - ' + str(self.id) + ' - ' + str(self.comment[0:20])


	
class Resort(models.Model):
	name = models.CharField(max_length=200)
	slug = models.SlugField(max_length=200)	
	branch = models.CharField(max_length=200,blank=True, null=True)
	description = models.TextField(blank=True, null=True)
	picture = models.ForeignKey(Photo, blank=True, null=True)
	email = models.EmailField(blank=True, null=True)
	url = models.URLField(blank=True, null=True)
	address = models.CharField(max_length=200, blank=True,)
	address_country = models.ForeignKey(Country,blank=True,null=True)
	premod = models.BooleanField(default=False)
	comment = models.ManyToManyField(Comment, blank=True, null=True)
	
	def __unicode__(self):
		return self.name
	class Meta:
		verbose_name = 'Resort'
		verbose_name_plural = 'Resorts'
		ordering = ('name',)


class Ad(models.Model):
	name = models.CharField(max_length=80)
	slug = models.SlugField(max_length=100)
	description = models.TextField()
	descriptionflat = models.TextField(blank=True)
	descriptionhtml = models.TextField(blank=True)
	photos = models.ManyToManyField(Photoo, blank=True, null=True)
	resort = models.ForeignKey(Resort, blank=True, null=True)
	creator = models.ForeignKey(User)
	start_ad = models.DateField(blank=True,auto_now_add=True)
	start_room = models.DateField(blank=True)
	end_room = models.DateField(blank=True)
	adtype = models.IntegerField(choices=ADTYPES,blank=True, null=True)
	premod = models.BooleanField(default=False)
	paid = models.BooleanField(default=False)
	expiration_date = models.DateField(blank=True,)
	price = models.DecimalField(max_digits=10, decimal_places=2)
	priceunit = models.IntegerField(choices=PRICETYPES,blank=True, null=True)
			# alter table ts_ad add column descriptionhtml longtext not null;
			# alter table ts_ad add column descriptionflat longtext not null;		
	class Meta:
		ordering = ('-start_ad',)
		permissions = (('view_paypal','Can see the results of Paypal auth return.'),)

	def __unicode__(self):
		return self.name

	def first(self):
		for photo in self.photos.all():
			if photo.orderer == 1:
				return photo
				break

	def photolist(self):
		return self.photos.order_by('orderer')

	def save(self,*args,**kwargs):
		s = self
		dhtml = _make_html_text(s.description)
		try:
			chtml = _sanitize_html(dhtml, valid_tags=VALID_TAGS)
		except Exception, e:
			chtml = "Sorry we can't retrieve this post right now."
		s.descriptionhtml = chtml
		s.descriptionflat = _make_flat_text(chtml)
		new = True
		try:		# this checks to see if it is new or not
			a = Ad.objects.get(id=s.id)
			new = False
			action = 'edited'
		except Exception, e:
			a = None
			action = 'created'
		super(Ad, self).save(*args,**kwargs)
		subject = 'TSR: An ad was just %s. %s'  %(action,self.name)
		content = '''Annie,
				%s just %s the ad %s.
				Check it for moderation <a href='http://timesharerentals.com/admin/ts/ad/%s/'>here</a> when you get a chance.
				
				Timesharerentals.com
		''' %(self.creator,action,self.name,self.id)
		fromemail = settings.CONTACT_EMAIL
		toemail = ['modernarrangements@gmail.com',]
		send_mail(subject,content,fromemail,toemail)



class Email(models.Model):
	EVENT_CHOICES = ((1,'Ad is Created'),(2,'TS is available'),(3,'TS is done being available'),(4,'Ad expires'),)
	name = models.CharField(max_length=100)
	content = models.TextField()
	days = models.IntegerField(blank=True, null=True)
	event = models.IntegerField(choices=EVENT_CHOICES,blank=True, null=True)
	
	def __unicode__(self):
		return self.name
		

apps/profiler/forms.py
# profiler/forms.py
from django import forms
from django.forms.models import ModelForm
from django.contrib.auth.models import User
from django.db.models import get_model
from django.forms.extras import widgets
from django.utils.translation import ugettext_lazy as _
from profiler.models import Mess


class LoginForm(forms.Form):
	username = forms.CharField(max_length=30,label='Username')
	password = forms.CharField(max_length=100,label='Password',widget=forms.PasswordInput)


class NewUserForm(forms.ModelForm):
	"""
	A form that creates a user, with no privileges, from the given username, email and password.
	"""
	username = forms.RegexField(label=_("Username"), max_length=30, regex=r'^\w+$',
		help_text = _("Required. 30 characters or fewer. Alphanumeric characters only (letters, digits and underscores)."),
		error_message = _("This value must contain only letters, numbers and underscores."))
	email = forms.EmailField(label=_("Email"),)
	password1 = forms.CharField(label=_("Password"), widget=forms.PasswordInput)
	password2 = forms.CharField(label=_("Password confirmation"), widget=forms.PasswordInput)

	class Meta:
		model = User
		fields = ("username",)

	def clean_username(self):
		username = self.cleaned_data["username"]
		try:
			User.objects.get(username=username)
		except User.DoesNotExist:
			return username
		raise forms.ValidationError(_("A user with that username already exists."))

	def clean_password2(self):
		password1 = self.cleaned_data.get("password1", "")
		password2 = self.cleaned_data["password2"]
		if password1 != password2:
			raise forms.ValidationError(_("The two password fields didn't match."))
		return password2

	def save(self, commit=True):
		user = super(UserCreationForm, self).save(commit=False)
		user.set_password(self.cleaned_data["password1"])
		if commit:
			user.save()
		return user
		
		
class MessForm(forms.ModelForm):
	# name = forms.CharField(widget=forms.TextInput(attrs={'size':'35'}))
	# description = forms.CharField(widget=forms.Textarea(attrs={'cols':'50'}))
	# addedresortname = forms.CharField(widget=forms.TextInput(attrs={'size':'35'}),label='Name of Resort',required=False)
	# start_room = forms.CharField(widget=forms.TextInput(attrs={'size':'8'}),label='Start Date')
	# end_room = forms.CharField(widget=forms.TextInput(attrs={'size':'8'}),label='End Date')
		
	class Meta:
		model = Mess
		exclude = ('unread','sender','receiver','replied','name','email',)

	def __init__(self, where, *args, **kwargs):
		super(MessForm, self).__init__(*args, **kwargs)
		if where == 0:
			self.fields['namer'] = forms.CharField(label='Name',help_text='htn',required=True,)
			self.fields['emailer'] = forms.EmailField(label='Email',help_text='hte',required=True,)



# 
# 
# 
# 	
# class LoginForm(forms.Form):
# 	username = forms.CharField(max_length=30,label='Username')
# 	password = forms.CharField(max_length=100,label='Password',widget=forms.PasswordInput)
	
	
class ForgotForm(forms.Form):
	email = forms.EmailField()
	
	def clean_email(self):
		data = self.cleaned_data['email']
		allusers = User.objects.all()
		inthere = False
		for auser in allusers:
			if auser.email == data:
				inthere = True
		if inthere == False:
			raise forms.ValidationError('That Email is not in our database')
		return data


class PasswordResetForm(forms.Form):
	new_password_1 = forms.CharField(max_length=16, widget=forms.PasswordInput, required=True,)
	new_password_2 = forms.CharField(max_length=16, widget=forms.PasswordInput, required=True,)
   
	def clean(self):
		cleaned_data = self.cleaned_data
		new_password_1 = cleaned_data.get('new_password_1')
		new_password_2 = cleaned_data.get('new_password_2')
		if new_password_1 and new_password_2:
			if (self.cleaned_data['new_password_1'] != self.cleaned_data['new_password_2']):
				raise forms.ValidationError("You entered two different passwords")
		return self.cleaned_data


class PasswordChangeForm(forms.Form):
	old_password = forms.CharField(max_length=30, widget=forms.PasswordInput, required=True,)
	new_password_1 = forms.CharField(max_length=30, widget=forms.PasswordInput, required=True,label='New Password')
	new_password_2 = forms.CharField(max_length=30, widget=forms.PasswordInput, required=True,label='New Password Again')

	def clean(self):
		cleaned_data = self.cleaned_data
		new_password_1 = cleaned_data.get('new_password_1')
		new_password_2 = cleaned_data.get('new_password_2')
		if new_password_1 and new_password_2:
			if (self.cleaned_data['new_password_1'] != self.cleaned_data['new_password_2']):
				raise forms.ValidationError("New Password and New Password Again did not match.")
		return self.cleaned_data



class EmailChangeForm(forms.Form):
	email = forms.EmailField()

		
		
class UserEditForm(forms.Form):
	# first_name = forms.CharField(max_length=30,label='First Name',required=True,)
	# last_name = forms.CharField(max_length=30,label='Last Name',required=True,)
	email = forms.EmailField(label='Email',required=True,)
	# class Meta:
		# model = get_model('auth', 'user')
		# exclude = ('username','password','is_staff','is_active','is_superuser','last_login','date_joined','groups','user_permissions',)
		
		
		
		
	

templates/profiler/forgot.html
{# templates/profile/forgot.html #}

{% extends "base.html" %}
{% block extra_head %}
	<style type="text/css" media="screen">
		#loginform{float:left;height:75px;margin:0 50px 0 50px;}
		#forgotform{float:left;height:75px;}
	</style>
{% endblock %}


{% block body %}

	<div class="section" id="wide_column">
		<div class='padder'>
			<h1>Forgot My Password</h1><br/>
			<div id='loginform'>
				{% if form.errors %}
					<p>That email is not in our database</p>
				{% endif %}

				<form action="{% url forgot_view %}" method="post">
					<table class="form-table">
						<tr>
							<td class="label">
								<label for="id_email">Email</label>
							</td>
							<td class="fields">
								{% if forgotform.email.errors %}<div>{{ forgotform.email.errors }}</div><br/>{% endif %}
								{{ forgotform.email }}
							</td>
						</tr>
						<tr>
							<td class="label">&nbsp;</td>
							<td class="fields">
								<input type="hidden" name="next" value="{{ next }}" />
								<input type="submit" name="submit" value="Submit" class="formbutton" id="post">
							</td>
						</tr>
					</table>
				</form>
			</div>{# end of loginform #}
			<div id='forgotform'>
				Enter the email address associated with your account and we will email you a link to reset your password.
			</div>{# end of signupform #}
			<div class='clearer'></div>
		</div>{# end of padder #}
	</div>{# end of section #}

{% endblock %}

templates/profiler/forgot_submit.html
{# templates/profile/forgot_submit.html #}

{% extends "base.html" %}


{% block body %}
	<div class="section" id="wide_column">
		<div class='padder'>
			<h1>An Email has been sent</h1><br/>
			<div id='loginform'>
				
				Follow the link in the email to reset your password.


			</div>{# end of loginform #}
			<div id='signupform'>
				{# Enter the email address associated with your account and we will email you a link to reset your password. #}
			</div>{# end of signupform #}
			<div class='clearer'></div>
		</div>{# end of padder #}
	</div>{# end of section #}
{% endblock %}

templates/profiler/login.html
{# templates/profile/login.html #}

{% extends "base.html" %}
{% block extra_head %}
	<style type="text/css" media="screen">
		#loginform{float:left;height:120px;margin:0 100px 0 150px;}
		#forgotform{float:left;height:120px;}
	</style>
{% endblock %}

{% block body %}
	<div class="section" id="wide_column">
		<div class='padder'>
			<h2>Login</h2><br/>
			{% if message %}<p>{{ message }}</p>{% endif %}

			<form action="{% url login_view %}" method="post" id='loginform'>
				<table class="form-table">
					<tr>
						<td class="label">
							<label for="id_name">Username</label>
						</td>
						<td class="fields">
							{% if loginform.username.errors %}<div>{{ loginform.username.errors }}</div><br/>{% endif %}
							{% if message %}<div><ul class='errorlist'><li>{{ message }}</li></ul></div><br/>{% endif %}
							{{ loginform.username }}
						</td>
					</tr>
					<tr>
						<td class="label">
							<label for="id_email">Password</label>
						</td>
						<td class="fields">
							{% if loginform.password.errors %}<div>{{ loginform.password.errors }}</div><br/>{% endif %}
							{{ loginform.password }}
						</td>
					</tr>
					<tr>
						<td class="label">&nbsp;</td>
						<td class="fields">
							<input type="hidden" name="next" value="{{ next }}" />
							<input type="submit" name="submit" value="Login" class="formbutton" id="post">
						</td>
					</tr>
				</table>
			</form>{# end of login form #}
			<form action="{% url forgot_view %}" method="get" id='forgotform'>
				<table class="form-table">
					<tr><td>I don't have an account yet</td><td><a href='{% url newuser %}'>Sign Up</a></td></tr>
					<tr>
						<td class="label"><label for='id_postforgot'>I forgot my password</label></td>
						<td class="fields">
							<input type="hidden" name="next" value="{{ next }}" />
							<input type="submit" name="submit" value="Forgot" class="formbutton" id="post_postforgot">
						</td>
					</tr>
				</table>
			</form>{# end of forgot form #}
			<div class='clearer'></div>
		</div>{# end of padder #}
	</div>{# end of section #}
{% endblock %}

templates/profiler/profile.html
{# templates/profiler/profile.html #}
{% extends "base.html" %}

{% block head_title %}{{ theuser }}{% endblock head_title %}
{% block extra_head %}
	<style type="text/css" media="screen">
		.paybutton{display:block;}
		.editer{width:42px;float:right;}
		.editerpic{width:42px;margin:0 auto;}
		.uploader{width:42px;margin:0 auto;}
		.dbuttoner{color:red;}
		.profilelinks{float:right;width:300px;border-bottom:1px solid gray;padding:0 0 0 20px;}
		.profilelinks li{float:left;border:1px solid gray;margin:0 10px -1px 0;padding:1px 10px 2px 10px;background:#e1c575;cursor:pointer;
			-moz-border-radius-topleft:4px;-moz-border-radius-topright:4px;-webkit-border-top-left-radius:4px;-webkit-border-top-right-radius:4px;}
		.profilelinks li.active{border-bottom:1px solid #F2D686;background:#F2D686;}
	</style>
{% endblock %}

{% block body %}
	<div class="section" id="wide_column">
		<div class='padder'>
			<ul class='profilelinks'>
				<li class='active'>Ads</li>
				<li><a href='{% url messages theuser.id %}'>Messages {% if mess %}{{ mess|length }}{% endif %}</a></li>
				<li><a href='{% url usersettings theuser.id %}'>Settings</a></li>
			</ul>
			
			<h1>{{ theuser }}'s Profile</h1><br/><br/>
		
			{% if me %}
				<h2 class='resortheader'><span>Ads</span></h2><br/><br/>
				<table id='profile'>
					<tr>
						<th>Name</th>
						<th>Approved</th>
						<th>Photo(s)</th>
						<th>Expires</th>
						<th>Type</th>
						<th>Description</th>
						<th>Paid</th>
						<th>Delete</th>
					</tr>
					{% for ad in ads %}
						<tr>
							<td><a href='{% url addetail ad.id ad.slug %}' class='proname'>{{ ad.name }}</a></td>
							<td><div class='premod{{ ad.premod }}'>&nbsp;</div></td>
							<td><div class='prothumb'>{% include 'includes/justthumbs.html' %}</div></td>
							<td><div class='expad'>{% ifequal ad.adtype 4 %}Lifetime{% else %}{{ ad.expiration_date|date:"F d" }}<br/>{{ ad.expiration_date|date:"Y" }}{% endifequal %}</div></td>
							<td><span class='medalholder{{ ad.adtype }}'></span><p class='promedti'>{{ ad.get_adtype_display }}</p></td>
							<td><p class='prodesc'>{{ ad.descriptionflat|truncatewords:"25" }}<a href='{% url ad_edit ad.id %}' class='buttoner editer'><span class='editad'>edit</span></a></p></td>
							<td><div class='paid'>{% if ad.paid %}
								<img src="/admin_media/img/admin/icon_success.gif" class="pic" alt="pic"></img>{% else %}
								<form action="https://www.paypal.com/cgi-bin/webscr" method="post">
								<input type="hidden" name="cmd" value="_s-xclick">
								<input type="hidden" name="item_number" value="{{ ad.id }}">
								<input type="hidden" name="hosted_button_id" value="{{ ad.paypalid }}">
								<input type="submit" name="submit" alt="PayPal" class='buttoner' value='pay now $' style='color:#7AAA1B;'>
								</form>{% endif %}</div>
							</td>
							<td><a href='{% url ad_delete ad.id %}' class='buttoner dbuttoner'><span class='deletead'>delete</span></a></td>
						</tr>
					{% endfor %}
				</table><br/><br/>
			{% else %} 		{# this is when other people come to your page. #}
				{% if paidmodads %}
					<h3>Timeshares</h3><br/>
					<ul>
						{% for ad in paidmodads %}
							<li><a href='{% url addetail ad.id ad.slug %}'>{{ ad }}</a></li>
						{% endfor %}
					</ul><br/>
				{% else %}
					{{ theuser }} doesn't have any timeshares ready to view.<br/><br/>
				{% endif %}
			{% endif %}
		
			TSR member since {{ theuser.date_joined|date:"F Y" }}
		</div>{# end of padder #}
	</div>{# end of section #}


{% endblock %}



tester
<form action="https://www.paypal.com/cgi-bin/webscr" method="post">
<input type="hidden" name="cmd" value="_s-xclick">
<input type="hidden" name="hosted_button_id" value="Z3U8KTPX7M4YU">
<input type="image" src="https://www.paypalobjects.com/en_US/i/btn/btn_paynow_LG.gif" border="0" name="submit" alt="PayPal - The safer, easier way to pay online!">
<img alt="" border="0" src="https://www.paypalobjects.com/en_US/i/scr/pixel.gif" width="1" height="1">
</form>



bronze
<form action="https://www.paypal.com/cgi-bin/webscr" method="post">
<input type="hidden" name="cmd" value="_s-xclick">
<input type="hidden" name="hosted_button_id" value="MBF7JSC4PLHYE">
<input type="image" src="https://www.paypalobjects.com/en_US/i/btn/btn_paynow_LG.gif" border="0" name="submit" alt="PayPal - The safer, easier way to pay online!">
<img alt="" border="0" src="https://www.paypalobjects.com/en_US/i/scr/pixel.gif" width="1" height="1">
</form>



silver
<form action="https://www.paypal.com/cgi-bin/webscr" method="post">
<input type="hidden" name="cmd" value="_s-xclick">
<input type="hidden" name="hosted_button_id" value="268KUB3QJEK3J">
<input type="image" src="https://www.paypalobjects.com/en_US/i/btn/btn_paynow_LG.gif" border="0" name="submit" alt="PayPal - The safer, easier way to pay online!">
<img alt="" border="0" src="https://www.paypalobjects.com/en_US/i/scr/pixel.gif" width="1" height="1">
</form>




gold
<form action="https://www.paypal.com/cgi-bin/webscr" method="post">
<input type="hidden" name="cmd" value="_s-xclick">
<input type="hidden" name="hosted_button_id" value="ZQ48W8J3LJZ8N">
<input type="image" src="https://www.paypalobjects.com/en_US/i/btn/btn_buynow_LG.gif" border="0" name="submit" alt="PayPal - The safer, easier way to pay online!">
<img alt="" border="0" src="https://www.paypalobjects.com/en_US/i/scr/pixel.gif" width="1" height="1">
</form>




{# http://tsr.travis.nu/ad/pay/success/ #}
{# http://tsr.travis.nu/ad/pay/cancel/ #}
{# notify_url=https://tsr.travis.nu/ad/pay/paypal/ #}