urls.py
from django.conf.urls.defaults import *
from django.conf import settings
from django.views.generic.simple import direct_to_template
from django.contrib import admin

import os.path

admin.autodiscover()

urlpatterns = patterns('',
	(r'^ads/', include('ts.urls')),
	(r'^calendar/', include('calendarer.urls')),
	(r'^contact/', include('contact.urls')),	
	(r'^profile/', include('profiler.urls')),
	(r'^photologue/', include('photologue.urls')),
	(r'^search/', include('search.urls')),
	(r'^pages/', include('pages.urls')),
	(r'^$', include('homepage.urls')),
    (r'^error/', include('redirect.urls')),
	(r'^admin/', include(admin.site.urls)),
    (r'^admin/doc/', include('django.contrib.admindocs.urls')),
	(r'^my_admin/jsi18n', 'django.views.i18n.javascript_catalog'),
)

if settings.DEBUG:
    urlpatterns += patterns('',
        (r'^site_media/(?P<path>.*)$', 'django.views.static.serve',
            {'document_root': os.path.join(os.path.dirname(__file__), "site_media")}),
    )

admin.site.root_path = '/admin/'

apps/ts/models.py
# ts/models.py
from django.db import models
from datetime import datetime, timedelta
from django.contrib.auth.models import User
from photologue.models import Photo, Gallery
from django.utils.safestring import mark_safe
import settings
if "mailer" in settings.INSTALLED_APPS:
    from mailer import send_mail
else:
    from django.core.mail import send_mail
from BeautifulSoup import BeautifulSoup
from BeautifulSoup import Comment as BSComment
from markdown import markdown


def _make_html_text(markdown_text):
	regular_text = markdown(markdown_text)
	return regular_text

VALID_TAGS = {'strong': [],'em': [],'p': [],'ol': [],'ul': [],'li': [],'br': [],'quote':[],'h1':[],'h2':[],'hr':[],'a': ['href', 'title'],'table':[],'tr':[],'th':[],'td':[],}

def _sanitize_html(value, valid_tags=VALID_TAGS):
    soup = BeautifulSoup(value)
    comments = soup.findAll(text=lambda text:isinstance(text, BSComment))
    [comment.extract() for comment in comments]
    # Some markup can be crafted to slip through BeautifulSoup's parser, so
    # we run this repeatedly until it generates the same output twice.
    newoutput = soup.renderContents()
    while 1:
        oldoutput = newoutput
        soup = BeautifulSoup(newoutput)
        for tag in soup.findAll(True):
            if tag.name not in valid_tags:
                tag.hidden = True
            else:
                tag.attrs = [(attr, value) for attr, value in tag.attrs if attr in valid_tags[tag.name]]
        newoutput = soup.renderContents()
        if oldoutput == newoutput:
            break
    return newoutput


def _make_flat_text(markdown_text):
	lineless = markdown_text.replace('\n',' ')
	spaceless = ''.join(BeautifulSoup(lineless).findAll(text=True))
	return spaceless
	
ADTYPES = ((1,'Free'),(2,'Bronze'),(3,'Silver'),(4,'Gold'),)
PRICETYPES = ((1,'Per Night'),(2,'Per Week'),)


class Photoo(Photo):
	orderer = models.IntegerField(default=1,blank=True, null=True)
	
	class Meta:
		ordering = ['orderer']
		get_latest_by = "orderer"
		
	def ad(self):
		try:
			return self.ad_set.all()[0]
		except Exception, e:
			return 'hello'
			
	def user(self):
		try:
			return self.ad_set.all()[0].creator
		except Exception, e:
			return 'hello'

class Country(models.Model):
	name = models.CharField(blank=True,  max_length=128)
	iso = models.CharField(max_length=20,)
	
	class Meta:
		verbose_name = 'Country'
		verbose_name_plural = 'Countries'
		ordering = ('name',)
		
	def __unicode__(self):
		return self.name
	
	def flag(self):
		return mark_safe('<img src="/site_media/images/flagsbig/' + str(self.iso) + '.png" style="width:80px;"></img>')
	flag.allow_tags=True


class Comment(models.Model):
	comment = models.TextField(blank=True)
	user = models.ForeignKey(User)
	premod = models.BooleanField(default=False)
	date_created = models.DateField(blank=True,auto_now_add=True)
	
	def __unicode__(self):
		return str(self.user) + ' - ' + str(self.id) + ' - ' + str(self.comment[0:20])


	
class Resort(models.Model):
	name = models.CharField(max_length=200)
	slug = models.SlugField(max_length=200)	
	branch = models.CharField(max_length=200,blank=True, null=True)
	description = models.TextField(blank=True, null=True)
	picture = models.ForeignKey(Photo, blank=True, null=True)
	email = models.EmailField(blank=True, null=True)
	url = models.URLField(blank=True, null=True)
	address = models.CharField(max_length=200, blank=True,)
	address_country = models.ForeignKey(Country,blank=True,null=True)
	premod = models.BooleanField(default=False)
	comment = models.ManyToManyField(Comment, blank=True, null=True)
	
	def __unicode__(self):
		return self.name
	class Meta:
		verbose_name = 'Resort'
		verbose_name_plural = 'Resorts'
		ordering = ('name',)


class Ad(models.Model):
	name = models.CharField(max_length=80)
	slug = models.SlugField(max_length=100)
	description = models.TextField()
	descriptionflat = models.TextField(blank=True)
	descriptionhtml = models.TextField(blank=True)
	photos = models.ManyToManyField(Photoo, blank=True, null=True)
	resort = models.ForeignKey(Resort, blank=True, null=True)
	creator = models.ForeignKey(User)
	start_ad = models.DateField(blank=True,auto_now_add=True)
	start_room = models.DateField(blank=True)
	end_room = models.DateField(blank=True)
	adtype = models.IntegerField(choices=ADTYPES,blank=True, null=True)
	premod = models.BooleanField(default=False)
	paid = models.BooleanField(default=False)
	expiration_date = models.DateField(blank=True,)
	price = models.DecimalField(max_digits=10, decimal_places=2)
	priceunit = models.IntegerField(choices=PRICETYPES,blank=True, null=True)
			# alter table ts_ad add column descriptionhtml longtext not null;
			# alter table ts_ad add column descriptionflat longtext not null;		
	class Meta:
		ordering = ('-start_ad',)
		permissions = (('view_paypal','Can see the results of Paypal auth return.'),)

	def __unicode__(self):
		return self.name

	def first(self):
		for photo in self.photos.all():
			if photo.orderer == 1:
				return photo
				break

	def photolist(self):
		return self.photos.order_by('orderer')

	def save(self,*args,**kwargs):
		s = self
		dhtml = _make_html_text(s.description)
		try:
			chtml = _sanitize_html(dhtml, valid_tags=VALID_TAGS)
		except Exception, e:
			chtml = "Sorry we can't retrieve this post right now."
		s.descriptionhtml = chtml
		s.descriptionflat = _make_flat_text(chtml)
		new = True
		try:		# this checks to see if it is new or not
			a = Ad.objects.get(id=s.id)
			new = False
			action = 'edited'
		except Exception, e:
			a = None
			action = 'created'
		super(Ad, self).save(*args,**kwargs)
		subject = 'TSR: An ad was just %s. %s'  %(action,self.name)
		content = '''Annie,
				%s just %s the ad %s.
				Check it for moderation <a href='http://timesharerentals.com/admin/ts/ad/%s/'>here</a> when you get a chance.
				
				Timesharerentals.com
		''' %(self.creator,action,self.name,self.id)
		fromemail = settings.CONTACT_EMAIL
		toemail = ['modernarrangements@gmail.com',]
		send_mail(subject,content,fromemail,toemail)



class Email(models.Model):
	EVENT_CHOICES = ((1,'Ad is Created'),(2,'TS is available'),(3,'TS is done being available'),(4,'Ad expires'),)
	name = models.CharField(max_length=100)
	content = models.TextField()
	days = models.IntegerField(blank=True, null=True)
	event = models.IntegerField(choices=EVENT_CHOICES,blank=True, null=True)
	
	def __unicode__(self):
		return self.name
		

templates/ads/addelete.html
{# templates/ads/addelete.html #}
{% extends "base.html" %}

{% block head_title %}{{ ad }}{% endblock head_title %}


{% block body %}
	<div class="section" id="wide_column">
		<div class='padder'>
			<div class='subpadder'>
				<div id='profile'>
					<h1>Delete</h1>
					<h2>{{ ad }}</h2><br/><br/>
					<a href='{% url profile user.id %}' class='buttoner' style='float:right;margin-right:20px;'>Go to my profile</a>
					Are you sure want to delete {{ ad }}?<br/>You can't undo this and you won't get a refund for your unused time.<br/>
					{# <a href='{% url ad_delete ad.id %}' class='buttoner' style='width:52px;color:red;'><span class='deletead'>delete</span></a> #}
					<form action="{% url ad_delete ad.id %}" method="post" accept-charset="utf-8">
						<input type="submit" value="delete" class='buttoner' style='width:52px;color:red;background:#eee url(/admin_media/img/admin/icon_deletelink.gif) no-repeat right;width:68px;'>
					</form>
				</div>{# end of profile #}	
			</div>{# end of subpadder #}
		</div>{# end of padder #}
	</div>{# end of section #}


{% endblock %}


{# <form action="https://www.paypal.com/cgi-bin/webscr" method="post"> #}
{# <input type="hidden" name="cmd" value="_s-xclick"> #}
{# <input type="hidden" name="hosted_button_id" value="GWMAUVWHJD2UU"> #}
{# <input type="image" src="https://www.paypalobjects.com/en_US/i/btn/btn_buynowCC_LG.gif" border="0" name="submit" alt="PayPal - The safer, easier way to pay online!"> #}
{# <img alt="" border="0" src="https://www.paypalobjects.com/en_US/i/scr/pixel.gif" width="1" height="1"> #}
{# </form> #}

templates/ads/addetail.html
{# templates/ads/addetail.html #}
{% extends "base.html" %}

{% block head_title %}{{ ad }}{% endblock head_title %}
{% block extra_head %}
	{% include "includes/photopickerhead.html" %}
	<style type="text/css" media="screen">
		.subpadder{padding:0px 20px;}
		.member{padding:20px 0 0 0;}
		.editer{width:42px;float:right;margin-right:21px;}
		.editad{height:20px;}
		.alert{font-size:13px;border:2px solid red;-moz-border-radius:5px;-webkit-border-radius:5px;padding:20px;margin:0 0 30px 0;}
		.red{font-weight:bold;font-size:15px;color:red;}
		.visitor{font-size:15px;padding:0 0 20px 0;}
	</style>
{% endblock %}

{% block body %}
	<div class="section" id="wide_column">
		<div class='padder'>
			<div class='subpadder'>

				{% if not ad.expired %}{# this checks to see if it is expired #}
					{% ifequal user ad.creator %}{# it is me, the ads creator #}
						<a href='{% url ad_edit ad.id %}' class='buttoner editer'><div class='editad'>edit</div></a>
						<div class="rowheader"><h1>{{ ad }}</h1></div>
						{% if ad.premod %}{# it has been approved #}
							{% if ad.paid %}{# it has been paid for #}
								{% include 'ads/adincludes/adbody.html' %}
							{% else %}{# premodded but not paid for yet, weird #}
								{% include "ads/adincludes/alertdollar.html" %}
								{% include 'ads/adincludes/adbody.html' %}
							{% endif %}{# paid #}
						{% else %}{# it has not been approved #}
							{% if ad.paid %}{# it has been paid for #}
								{% include "ads/adincludes/alertmod.html" %}
								{% include 'ads/adincludes/adbody.html' %}
							{% else %}{# it has not been paid for #}
								{% include "ads/adincludes/alertdollar.html" %}
								{% include "ads/adincludes/alertmod.html" %}
								{% include 'ads/adincludes/adbody.html' %}
							{% endif %}{# end of paid for #}
						{% endif %}{# end of premod #}
					{% else %}{# I am not the creator but I am viewing it #}
						{% if ad.premod %}{# it has been approved #}
							{% if ad.paid %}{# it has been paid for #}
								<div class="rowheader"><h1>{{ ad }}</h1></div>
								{% include 'ads/adincludes/adbody.html' %}
							{% else %}{# premodded but not paid for yet, weird #}
								{% include "ads/adincludes/alertvisitor.html" %}
							{% endif %}{# paid #}
						{% else %}{# it has not been approved #}
							{% include "ads/adincludes/alertvisitor.html" %}
						{% endif %}{# end of premod #}
					{% endifequal %} {# end of it is me check #}
				{% else %}	{# it is expired #}
					{% ifequal user ad.creator %}{# it is me, the ads creator #}
						This ad has expired. You can renew it <a href='{% url profile ad.creator.id %}'>here</a>.
					{% else %}{# I am not the creator but I am viewing it #}
						This ad has expired.
					{% endifequal %} {# end of it is me check #}
				{% endif %} {# expired check #}
				
			</div>{# end of subpadder #}
		</div>{# end of padder #}
	</div>{# end of section #}


{% endblock %}


{# if me  #}
{# 	yes - show title and check for premod #}
{# 		yes - check for paid #}
{# 			yes-show ad #}
{# 			no-show $ message #}
{# 		no - check for paid #}
{# 			yes - show me message about mod #}
{# 			no - show me message and $ message #}
{# 			 #}
{# 	 #}
{# 	no - Don't show title and do check for premod #}
{# 		yes-check for paid #}
{# 			yes - show ad #}
{# 			no - show message to visitor #}
{# 		no-show message to visitor #}
		
		
		
		

templates/ads/adedit.html
{# templates/ads/adedit.html #}
{% extends "base.html" %}

{% block head_title %}Edit -- {{ ad }}{% endblock head_title %}

{% block body %}
	<div class="section" id="wide_column">
		<div class="row">
			{% if ad.premod %}
				<div class="rowheader">Edit -- {{ ad }}<span><a href='{% url createpictures ad.id %}'>Upload Pictures</a></span></div>
				<div>
					{% for photo in ad.photos.all %}
						<img src="{{ photo.get_thumbnail_url }}" class="pic" alt="{{ photo }}"></img>
					{% endfor %}
					<div>
						{{ ad.description }}
					</div><br/>
					<div>
						<a href='{% url profile user.id %}'>{{ user }}</a>
					</div>
				</div>
				<div class='clearer'></div>
			{% else %}
				<div class="rowheader">This ad is waiting to be approved</div><br/><br/>
				{% ifequal request.user ad.creator %}
					<div class="rowheader">{{ ad }}</div>
					<div>
						{% for photo in ad.photos.all %}
							<img src="{{ photo.get_thumbnail_url }}" class="pic" alt="{{ photo }}"></img>
						{% endfor %}
						<div>
							{{ ad.description }}
						</div><br/>
						<div>
							<a href='{% url profile user.id %}'>{{ user }}</a>
						</div>
						<div class='clearer'></div>
					</div>
				{% endifequal %}
			{% endif %}
		</div>{# end of row #}
	</div>


{% endblock %}

templates/ads/adlist.html
{# templates/ads/adlist.html #}
{% extends "base.html" %}

{% load gravatar %}
{% load date_range %}

{% block head_title %}Ad List{% endblock head_title %}

{% block extra_head %}
	<script type="text/javascript" charset="utf-8">
		$(document).ready(function(){
			sort = '{{ sort }}';
			direc = '{{ direc }}';
			$('#' + sort).addClass('active').addClass(direc);
			if(direc == 'asc'){
				current = $('#' + sort).attr('href');
				current = current + '&direc=desc';
				$('#' + sort).attr('href',current);
			}
			$('#desc').click(function(e){
				e.preventDefault();
			})
		});
	</script>
	<style type="text/css" media="screen">
		.searchholder{padding:0 0 10px 0;}
	</style>
{% endblock %}

{% block body %}
	<div class="section" id="wide_column">
		<div class='row'>
			<div class='googleadwidelist'>
				{# Here are some Google Ads #}
				{% include "includes/googleadwide.html" %}				
			</div>
			<div class='searchholder'>{% include "includes/searchbox.html" %}</div>
			<div class='clearer'></div>
		</div>
		<div class='rowtitle'>
			<a href='?sort=name' class='rowtitlet' id='name'>Name</a>
			<a href='?sort=date' class='rowtitlet' id='date'>Date</a>
			<a href='' class='rowtitlet' id='desc'>Description</a>
			<a href='?sort=resort' class='rowtitlet' id='resort'>Resort</a>
			<a href='?sort=country' class='rowtitlet' id='country'>Country</a>
			<a href='?sort=price' class='rowtitlet' id='price'>Price</a>
		</div>
		
		{% for ad in ads.object_list %}
			<div class="row{% ifequal ad.adtype 1 %} rowfree{% else %} rowprem{% endifequal %}">
				<div class="rowleft">
					<a href="{% url addetail ad.id ad.slug %}">{{ ad.name }}</a>
					<div class='rowdate'>
						Available<br/>{% display_range ad.start_room ad.end_room %}
						{# {{ ad.start_room|date:'M d' }} - {{ ad.end_room|date:'d, Y' }} #}
					</div>
				
				</div>{# end of rowheader #}
				<div class='rowright'>
					{% ifnotequal ad.adtype 1 %}
						<div class='rowphotos'>
							{% for photo in ad.photos.all %}
								{% ifequal forloop.counter 1 %}
									<img src="{{ photo.get_thumbnail_url }}" class="pic" alt="{{ photo }}"></img>
								{% endifequal %}
								{% ifequal forloop.counter 2 %}
									<img src="{{ photo.get_thumbnail_url }}" class="pic" alt="{{ photo }}"></img>
								{% endifequal %}
							{% endfor %}
						</div>
					{% endifnotequal %}
					<div class='rowdescription'>
						{{ ad.descriptionflat|truncatewords:17 }}
					</div>
					<div class='rowresort'>
						{{ ad.resort }}<br/>
						{# <img src="{{ ad.resort.picture.get_fingernail_url }}" class="pic" alt="{{ photo }}"></img> #}
					</div>
					<div class='rowcountry'>
						<img src="/site_media/images/flagsbig/{{ ad.resort.address_country.iso }}.png" class="pic" alt="{{ ad.resort.address_country }}"></img>
						<p>{{ ad.resort.address_country }}</p>
					</div>
					<div class='rowprice'>$ {{ ad.price }}<br/>{{ ad.get_priceunit_display }}</div>
					{# <div>{{ ad.adtype }}</div> #}
				</div>{# end of rowfooter #}
			</div>{# end of row #}<div class='clearer'></div>
		{% endfor %}
		<div class="pagination">
		    <span class="step-links">
		        {% if ads.has_previous %}
		            <a href="?page={{ ads.previous_page_number }}&amp;sort={{ sort }}&amp;direc={{ direc }}">previous</a>
		        {% endif %}

		        <span class="current">
		            Page {{ ads.number }} of {{ ads.paginator.num_pages }}.
		        </span>

		        {% if ads.has_next %}
		            <a href="?page={{ ads.next_page_number }}&amp;sort={{ sort }}&amp;direc={{ direc }}">next</a>
		        {% endif %}
		    </span>
		</div>
		<div class='googleadwidelist'>
			{% include "includes/googleadwide.html" %}
		</div>
	</div>{# end of section #}

{% endblock %}










               

templates/ads/paycancel.html
{# templates/ads/paycancel.html #}
{% extends "base.html" %}

{% load gravatar %}

{% block head_title %}Paypal Canceled Payment{% endblock head_title %}


{% block body %}
	<div class="section" id="wide_column">
		
		Paypal - Payment Canceled
	</div>{# end of section #}

{% endblock %}










               

templates/ads/paypal.html
{# templates/ads/paycancel.html #}
{% extends "base.html" %}

{% load gravatar %}

{% block head_title %}Paypal Returned Values{% endblock head_title %}


{% block body %}
	<div class="section" id="wide_column">
		
		Paypal - Secret Values returned
	</div>{# end of section #}

{% endblock %}










               

templates/ads/paysuccess.html
{# templates/ads/paysuccess.html #}
{% extends "base.html" %}

{% load gravatar %}

{% block head_title %}Paypal Successful Payment{% endblock head_title %}


{% block body %}
	<div class="section" id="wide_column">
		
		Paypal - Payment Successful
	</div>{# end of section #}

{% endblock %}










               